Abbreviate ". ";
Abbreviate ", ";
Abbreviate "No ";
Abbreviate "├ís ";
Abbreviate "puedes ";
Abbreviate "_to/";
Abbreviate "├¡ ";
Abbreviate "├│n";
Abbreviate "├¡a";
Abbreviate "est";
Abbreviate "ent";
Abbreviate "que ";
Abbreviate "cerr";
Abbreviate "en ";
Abbreviate "Inform ";
Abbreviate "de ";
Abbreviate "Est";
Abbreviate "Per";
Abbreviate "├¡.";
Abbreviate "da ";
Abbreviate "con";
Abbreviate "descri";
Abbreviate "lleva";
Abbreviate "as ";
Abbreviate "es ";
Abbreviate "o s";
Abbreviate "o p";
Abbreviate "er ";
Abbreviate "ien";
Abbreviate "and";
Abbreviate "rec";
Abbreviate "te ";
Abbreviate "hay ";
Abbreviate "LookMod";
Abbreviate "inesperado.";
Abbreviate "obre ";
Abbreviate "Ya ";
Abbreviate "Te ";
Abbreviate "ar ";
Abbreviate "ion";
Abbreviate "├®n";
Abbreviate "el ";
Abbreviate "├í ";
Abbreviate "objec";
Abbreviate "espec";
Abbreviate "abl";
Abbreviate "ell";
Abbreviate "os ";
Abbreviate "una ";
Abbreviate "mism";
Abbreviate "ada.";
Abbreviate "or ";
Abbreviate "ado";
Abbreviate " co";
Abbreviate " primero";
Abbreviate " vac├¡";
Abbreviate "end";
Abbreviate "nter";
Abbreviate "Qui";
Abbreviate " juego";
Abbreviate " qu";
Abbreviate " no";
Abbreviate "per";
Abbreviate " pu";