Abbreviate ". ";
Abbreviate ", ";
Abbreviate "No ";
Abbreviate "ás ";
Abbreviate "puedes ";
Abbreviate "_to/";
Abbreviate "í ";
Abbreviate "ón";
Abbreviate "ía";
Abbreviate "est";
Abbreviate "que ";
Abbreviate "ent";
Abbreviate "cerr";
Abbreviate "en ";
Abbreviate "Inform ";
Abbreviate "de ";
Abbreviate "Est";
Abbreviate "Per";
Abbreviate "í.";
Abbreviate "da ";
Abbreviate "con";
Abbreviate "levas";
Abbreviate "descri";
Abbreviate "es ";
Abbreviate "as ";
Abbreviate "o s";
Abbreviate "o p";
Abbreviate "er ";
Abbreviate "tien";
Abbreviate "rec";
Abbreviate "te ";
Abbreviate "hay ";
Abbreviate "inesperado.";
Abbreviate "LookMod";
Abbreviate "obre ";
Abbreviate "Ya ";
Abbreviate "Te ";
Abbreviate "á ";
Abbreviate "án";
Abbreviate "ar ";
Abbreviate "ion";
Abbreviate "én";
Abbreviate "el ";
Abbreviate "objec";
Abbreviate "espec";
Abbreviate "abl";
Abbreviate "ell";
Abbreviate "os ";
Abbreviate "ued";
Abbreviate "mism";
Abbreviate "alg";
Abbreviate "ada.";
Abbreviate "and";
Abbreviate "do ";
Abbreviate "rimero";
Abbreviate "nte";
Abbreviate "no ";
Abbreviate "Qui";
Abbreviate "se ";
Abbreviate "rea";
Abbreviate "juego";
Abbreviate "re ";
Abbreviate "lo ";
Abbreviate "Tie";